server:
  port: 44001
spring:
  application:
    name: dubbo-client-second
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  main:
    allow-bean-definition-overriding: true
dubbo:
  protocol:
    name: dubbo
    port: -1
  cloud:
    subscribed-services: dubbo-client-first