server:
  port: 20020
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: laboratory-nacos-cosumer
management:
  endpoints:
    web:
      exposure:
        include: \*